### ISSUE TITLE
Latest Serilog with latest Nuget.exe causes 'Serilog' already has a dependency defined for 'Microsoft.CSharp'

### ISSUE THREAD

**Issue by ATripathy1** [serilog/serilog#1016]
I have upgraded to the latest nuget versions for Micorosoft Visual Studio 2015. 

Name             : Package Manager Host
Version          : 3.5.0.1996
InstanceId       : ac02c4e6-7c58-47ca-81ce-d16dcde804ca
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface

Severity	Code	Description	Project	File	Line	Suppression State
Error		'Serilog' already has a dependency defined for 'Microsoft.CSharp'.
   at NuGet.Manifest.ValidateDependencySets(IPackageMetadata metadata)
   at NuGet.Manifest.Validate(Manifest manifest)
   at NuGet.Manifest.ReadFrom(Stream stream, IPropertyProvider propertyProvider, Boolean validateSchema)
   at NuGet.LocalPackage.ReadManifest(Stream manifestStream)
   at NuGet.OptimizedZipPackage.EnsureManifest()
   at NuGet.OptimizedZipPackage..ctor(IFileSystem fileSystem, String packagePath)
   at NuGet.LocalPackageRepository.OpenPackage(String path)
   at NuGet.LocalPackageRepository.GetPackage(Func`2 openPackage, String path)
   at NuGet.LocalPackageRepository.<>c__DisplayClass13.<FindPackage>b__f(String path)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at NuGet.LocalPackageRepository.FindPackage(Func`2 openPackage, String packageId, SemanticVersion version)
   at NuGet.LocalPackageRepository.FindPackage(String packageId, SemanticVersion version)
   at JFrog.Artifactory.Utils.BuildInfoExtractor.addDependencies(String projectName, Module module, String localSource, String[] packageConfigPath, String Configuration)
   at JFrog.Artifactory.Utils.BuildInfoExtractor.ProccessModule(Build build, ProjectModel project, ArtifactoryBuild _task)
   at JFrog.Artifactory.Utils.SolutionHandler.ProccessModuleRef()
   at JFrog.Artifactory.Utils.SolutionHandler.Execute()
   at JFrog.Artifactory.ArtifactoryBuild.Execute()	Artifactory

**Comment by nblumhardt** [comment]
Thanks for the post. Which Serilog version are you installing, and what is the target framework for the project you're installing it into?

I've seen some of these kinds of things turn out to be machine-specific (bad caches and so on) - if you have another machine handy to try it on, that would also be useful info. Thanks!

**Comment by ATripathy1** [comment]
@nblumhardt I have tested this on multiple machines and the problem seems to be consistent. Target Framework is for 4.5.2.

**Comment by nblumhardt** [comment]
Interesting, thanks. I can't repro, but I'm running VS2017. Assuming that there must be other users installing Serilog under 2015 though, so not sure why this would affect you and not everyone else. Anything special about the environment you're working in? Cheers!

**Comment by nblumhardt** [comment]
Hi @ATripathy1 - hope all is going well - any additional clues here?

Regards,
Nick

**Comment by nblumhardt** [comment]
Will close for now, please drop us a line if you are still experiencing the issue or have more ideas for how we could chase this.
