### ISSUE TITLE
Serilog fails to log JSON object with empty-string properties

### ISSUE THREAD

**Issue by andrewslavin** [serilog/serilog#1127]
I use Serilog.AspNetCore in Asp.Net Core 2.0 web api project. I also use Destructurama.JsonNet to log JSON objects as structured data. Now here's the issue:

1. If you send a POST request with empty body to an Asp.Net Core 2.0 web api endpoint, it will reply with a 400 response. Content-type is `application/json`, and body is `{"":["A non-empty request body is required."]}`.
1. I log requests to and responses from my api. When I log this particular response, I can see that content-type is JSON, so I read the body to string and then deserialize it using `Newtonsoft.Json.JsonConvert.DeserializeObject()`.
1. Then I log the result of deserialization with Serilog, and get an exception
```
System.ArgumentException: Property name is not valid.
   at Serilog.Events.LogEventProperty..ctor(String name, LogEventPropertyValue value)
   at Destructurama.JsonNet.JsonNetDestructuringPolicy.Destructure(JObject jo, ILogEventPropertyValueFactory propertyValueFactory)
   at Destructurama.JsonNet.JsonNetDestructuringPolicy.TryDestructure(Object value, ILogEventPropertyValueFactory propertyValueFactory, LogEventPropertyValue& result)
   at Serilog.Capturing.PropertyValueConverter.CreatePropertyValue(Object value, Destructuring destructuring, Int32 depth)
   at Serilog.Capturing.PropertyValueConverter.DepthLimiter.CreatePropertyValue(Object value, Destructuring destructuring)
   at Serilog.Capturing.PropertyValueConverter.<<TryConvertEnumerable>g__MapToDictionaryElements14_0>d.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Serilog.Events.DictionaryValue..ctor(IEnumerable`1 elements)
   at Serilog.Capturing.PropertyValueConverter.TryConvertEnumerable(Object value, Destructuring destructuring, Type valueType, LogEventPropertyValue& result)
   at Serilog.Capturing.PropertyValueConverter.CreatePropertyValue(Object value, Destructuring destructuring, Int32 depth)
   at Serilog.Core.Logger.BindProperty(String propertyName, Object value, Boolean destructureObjects, LogEventProperty& property)
   at Serilog.Extensions.Logging.SerilogLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerExtensions.LogDebug(ILogger logger, String message, Object[] args)
   at ... my code here ...
```

I can see the exception is being thrown here [https://github.com/serilog/serilog/blob/32e0c9578db720add74720bceb62bd46967694c4/src/Serilog/Events/LogEventProperty.cs](url), because empty string JSON property name does not pass the `IsValidName(string name)` validation. Is it possible to remove this validation and allow any name string? `JsonConvert.DeserializeObject()` does not complain about empty string property names.

**Comment by nblumhardt** [comment]
Hi @andrewslavin - thanks for the report!

I think the bug here is with `Destructurama.JsonNet` - when a JSON object has an empty-string key, it needs to be logged through Serilog as a `DictionaryValue` instead of as a `StructureValue`. Removing the constraint on structure member names being non-empty could break other components downstream.

Any help over on the Destructurama side appreciated! I'll move the issue over there.
