### ISSUE TITLE
Logger formatting exception with repeated index arguments

### ISSUE THREAD

**Issue by jag43** [serilog/serilog#1247]
Bug

**What version of Serilog is affected?  Please list the related NuGet package.**
`Serilog 2.5.0`

**What is the target framework and operating system?**
`netcoreapp2.1`

**Please describe the current behavior?**
When attempting to write a log formatted with index arguments, an exception is thrown. It seems like this only occurs if one of the arguments is referenced more than once:
e.g. 
``` c#
logger.LogError("p1 {1}, {0}p2 {2}{0}",
    Environment.NewLine,
    10,
    20);
```
Exception message
```
An error occurred while writing to logger(s). (Index was outside the bounds of the array.)
```
Stack trace
```
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
   at Microsoft.Extensions.Logging.LoggerExtensions.LogError(ILogger logger, String message, Object[] args)
   at SerilogFormatError.Program.Main(String[] args) in C:\Users\source\repos\SerilogFormatError\SerilogFormatError\Program.cs:line 35
```

This works fine if accessing the serilogs logger directly, but errors when done through the Microsoft `ILogger`.

I expect this is more likely to be down to my misuse or a Microsoft problem but I thought I would check with you guys before asking them.

**Please describe the expected behavior?**
No exception and the log is written as expected.

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**

``` c#
using System;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Serilog;

namespace SerilogFormatError
{
    class Program
    {
        static void Main(string[] args)
        {
            var cfg = new LoggerConfiguration()
                .WriteTo.Console();

            Log.Logger = cfg.CreateLogger();

            var serviceCollection = new ServiceCollection();
            serviceCollection.AddSingleton(new LoggerFactory()
                .AddSerilog());
            serviceCollection.AddLogging();

            var services = serviceCollection.BuildServiceProvider();

            var logger = services.GetRequiredService<ILogger<Program>>();

            Console.WriteLine("Log using SeriLog Logger");

            Log.Error("p1 {1}, {0}p2 {2}{0}",
                Environment.NewLine,
                10,
                20);

            Console.WriteLine("Log using Microsoft ILogger");

            logger.LogError("p1 {1}, {0}p2 {2}{0}",
                Environment.NewLine,
                10,
                20);

            Console.ReadLine();
        }
    }
}
```

**Comment by jag43** [comment]
I changed the `LoggerFactory.AddSerilog()` to `LoggerFactory.AddConsole()` and the exception is still being thrown. I will make an issue on the `/aspnet/Extensions`

**Comment by jag43** [comment]
Here is the `aspnet` in case it helps anyone/they are interested https://github.com/aspnet/Extensions/issues/550

**Comment by nblumhardt** [comment]
Thanks for the follow-up. If you switch to `UseSerilog()` in https://github.com/serilog/serilog-aspnetcore you might be able to avoid this code path entirely (YMMV!) :-) Cheers!

**Comment by jag43** [comment]
Thanks for the tip, it looks like the problem is still happening though.
Exception
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.Extensions.Logging.Internal.LogValuesFormatter.GetValue(Object[] values, Int32 index)
   at Microsoft.Extensions.Logging.Internal.FormattedLogValues.GetEnumerator()+MoveNext()
   at Serilog.Extensions.Logging.SerilogLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
   at Microsoft.Extensions.Logging.LoggerExtensions.LogError(ILogger logger, String message, Object[] args)
   at SerilogFormatError.Startup.<>c.<<Configure>b__1_0>d.MoveNext() in C:\Users\source\repos\SerilogFormatError\SerilogFormatError\Program.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.TestHost.HttpContextBuilder.<>c__DisplayClass10_0.<<SendAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.TestHost.ClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at SerilogFormatError.Program.Main(String[] args) in C:\Users\source\repos\SerilogFormatError\SerilogFormatError\Program.cs:line 35
```
Program.cs
``` c#
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.TestHost;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Serilog;
using Serilog.Events;

namespace SerilogFormatError
{
    class Program
    {
        static async Task Main(string[] args)
        {
            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
                .Enrich.FromLogContext()
                .WriteTo.Console()
                .CreateLogger();

            try
            {
                var webHostBuilder = WebHost.CreateDefaultBuilder()
                    .UseStartup<Startup>()
                    .UseSerilog();
                using (var testServer = new TestServer(webHostBuilder))
                {
                    using (var client = testServer.CreateClient())
                    {
                        var result = await client.GetAsync("");
                        Console.WriteLine(await result.Content.ReadAsStringAsync());
                    }
                }
            }
            catch (Exception ex)
            {
                Log.Fatal(ex, "Host terminated unexpectedly");
            }
            finally
            {
                Log.CloseAndFlush();
            }
            
            Console.ReadLine();
        }
    }
    class Startup
    {
        public void ConfigureServices(
            IServiceCollection services)
        {

        }

        public void Configure(
            IApplicationBuilder app,
            IHostingEnvironment env,
            ILoggerFactory loggerFactory)
        {
            app.Run(async ctx =>
            {
                var logger = ctx.RequestServices.GetRequiredService<ILogger<Program>>();

                // this throws an error
                logger.LogError("p1 {1}, {0}p2 {2}{0}",
                    Environment.NewLine,
                    10,
                    20);

                await ctx.Response.WriteAsync("OK");
            });
        }
    }
}
```

**Comment by nblumhardt** [comment]
Ah, that's a shame. Thanks for letting me know. Following the progress of the MEL issue.

**Comment by GraemeF** [comment]
Could someone link to the issue please? Wondering if I have run into the same :)

**Comment by nblumhardt** [comment]
@GraemeF https://github.com/aspnet/Extensions/issues/550
