### ISSUE TITLE
Exception while emitting periodic batch from Serilog.Sinks.Elasticsearch.Durable.ElasticsearchLogShipper

### ISSUE THREAD

**Issue by Venkateshjsoft** [serilog/serilog#1343]
2019-07-11T09:24:35.2593454Z Exception while emitting periodic batch from Serilog.Sinks.Elasticsearch.Durable.ElasticsearchLogShipper: System.MissingMethodException: Method not found: '!!0 Elasticsearch.Net.ElasticLowLevelClient.IndicesPutTemplateForAll(System.String, Elasticsearch.Net.PostData, Elasticsearch.Net.PutIndexTemplateRequestParameters)'.
   at Serilog.Sinks.Elasticsearch.ElasticsearchSinkState.RegisterTemplateIfNeeded()
   at Serilog.Sinks.Elasticsearch.Durable.ElasticsearchLogShipper.<OnTick>d__3.MoveNext()

**Comment by nblumhardt** [comment]
Hi! Looks like your version of _Elasticsearch.Net_ is out of sync with what the package requires. Can you please post your package configuration? I'll also transfer this to the ES sink repo, where people with knowledge of the ES ecosystem lurk :-) Cheers!
