### ISSUE TITLE
Serilog MinimumLevel "Microsoft" Override ignoring some Microsoft log events

### ISSUE THREAD

**Issue by beevik** [serilog/serilog#1390]
Serilog 2.9.0
.NET core 3.0

Until recently I have been able to successfully override the default minimum logging level for all `Microsoft` assembly log events.  I did this with the following appsettings configuration:

```json
{
    "Serilog": {
        "MinimumLevel": {
            "Default": "Verbose",
            "Override": {
                "System": "Warning",
                "Microsoft": "Warning"
            }
        }
    }
}
```

Recently, however, I've noticed some "debug" and "info" `Microsoft` log events leaking through this filter.  In particular, some of the ASP.NET Core 3.0 authentication log events are leaking through.

I double-checked my appsettings files (including all developer appsettings files) to make sure I wasn't accidentally overriding the default Serilog minimum level values.

I wrote a log enricher to include the stack trace of each logged message.  Here is once such inappropriately logged `Microsoft` event along with its stack trace:
```
[17:17:11 INF] AuthenticationScheme: app was challenged.
   at App.Server.Core.Logging.LoggingStackTraceEnricher.Enrich(LogEvent logEvent, ILogEventPropertyFactory propertyFactory)
   at Serilog.Core.Logger.Dispatch(LogEvent logEvent)
   at Serilog.Core.Logger.Serilog.Core.ILogEventSink.Emit(LogEvent logEvent)
   at Serilog.Core.Logger.Dispatch(LogEvent logEvent)
   at Serilog.Core.Logger.Serilog.Core.ILogEventSink.Emit(LogEvent logEvent)
   at Serilog.Core.Logger.Dispatch(LogEvent logEvent)
   at Serilog.Core.Logger.Write(LogEvent logEvent)
   at Serilog.Extensions.Logging.SerilogLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass5_0`1.<Define>g__Log|0(ILogger logger, T1 arg1, Exception exception)
   at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass5_0`1.<Define>b__1(ILogger logger, T1 arg1, Exception exception)
   at Microsoft.Extensions.Logging.LoggingExtensions.AuthenticationSchemeChallenged(ILogger logger, String authenticationScheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationHttpContextExtensions.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationHttpContextExtensions.ChallengeAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at App.Server.Core.Common.Mvc.MvcExceptionMiddleware.Invoke(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at App.Server.Core.Common.Mvc.MvcExceptionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Hosting.HostingApplication.ProcessRequestAsync(Context context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection.ProcessRequestsAsync[TContext](IHttpApplication`1 httpApplication)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection.ProcessRequestsAsync[TContext](IHttpApplication`1 httpApplication)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnectionMiddleware`1.OnConnectionAsync(ConnectionContext connectionContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection.ExecuteAsync()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection.ExecuteAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

Here is the relevant [source code for ASP.NET Core](https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/Core/src/LoggingExtensions.cs). The delegate causing the unfiltered logging is the one called `_authenticationSchemeAuthenticated`.  

**Does this issue relate to a new *feature* or an existing *bug*?**
- [X] Bug
- [ ] New Feature

**What version of Serilog is affected?  Please list the related NuGet package.**

Serilog 2.9.0
Serilog.AspNetCore 3.1.0
Serilog.Sinks.Console 3.1.1

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [X] netCore 3.0
- [ ] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Comment by nblumhardt** [comment]
Thanks for the note! If you add `{SourceContext}` to your output template, do you see the expected (fully-qualified type name) values?

**Comment by beevik** [comment]
Thanks for the advice to try `{SourceContext}`.  This revealed that the message was being logged by a context in my application's namespace.  It looks like this happened because I am getting an `ILoggerFactory` from DI but passing it to a `Microsoft`-namespace base class.
 
Closing this issue, since it's a bug in my code.

**Comment by OlegMursalov** [comment]
O LOVE IT!
