### ISSUE TITLE
ReadyToRun Compilation does not work with Serilog

### ISSUE THREAD

**Issue by HolyOne** [serilog/serilog#1626]
Hello, I use serilog in my project and it works well whenI run the project from VS.

But when I publish my project (.net 6 rc1) with single executable option and with readyto run compilation, I get the following error.

If I completely remove serilog from startup, my application starts with no errors so I am sure serilog is the problem.

`
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Serilog.Sinks.Console, Version=4.0.1.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'. The system cannot find the file specified.
File name: 'Serilog.Sinks.Console, Version=4.0.1.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'
   at SeoSite.Web.Startup.ConfigureServices(IServiceCollection services) in D:\Projects\onlinetrackingnumber\SeoSite.Core\SeoSite.Web\Startup.cs:line 256
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at SeoSite.Web.Program.Main(String[] args) in D:\Projects\onlinetrackingnumber\SeoSite.Core\SeoSite.Web\Program.cs:line 17
`

**Comment by nblumhardt** [comment]
Hi Aytek; this one doesn't look likely to be a Serilog issue; Serilog.Sinks.Console is a pretty normal kind of assembly. Guessing that there's some build/packaging problem involved in this.

If you find any additional clues it would be great to learn how this is being triggered. I don't think there's anything we can do directly here, though.

**Comment by HolyOne** [comment]
Sorry, there was some serious changes with System.IO.Path.Combine function in .net 6 so It was not about serilog at all
Thanks
