### ISSUE TITLE
Serilog Crashed if we set Minimum log level to DEBUG(All Caps)

### ISSUE THREAD

**Issue by ganesh-darandale** [serilog/serilog#1661]
**Description**
Serilog Crashed if we set Minimum log level to DEBUG(All Caps)

**Reproduction**
 "Serilog": {
    "MinimumLevel": {
      "Default": "DEBUG",

**Expected behavior**
No exception should throw if we provide sme log level in Cpas

**Relevant package, tooling and runtime versions**
What Serilog version are you using, on what platform?
serilog.aspnetcore\4.1.0

**Additional context**
Exp -> The value DEBUG is not a valid Serilog level.

Stack -> at Serilog.Settings.Configuration.ConfigurationReader.ParseLogEventLevel(String value)
   at Serilog.Settings.Configuration.ConfigurationReader.<ApplyMinimumLevel>g__ApplyMinimumLevel|9_1(IConfigurationSection directive, Action`2 applyConfigAction, <>c__DisplayClass9_0& )
   at Serilog.Settings.Configuration.ConfigurationReader.ApplyMinimumLevel(LoggerConfiguration loggerConfiguration)
   at Serilog.Settings.Configuration.ConfigurationReader.Configure(LoggerConfiguration loggerConfiguration)
   at Serilog.Configuration.LoggerSettingsConfiguration.Settings(ILoggerSettings settings)
   at Serilog.ConfigurationLoggerConfigurationExtensions.Configuration(LoggerSettingsConfiguration settingConfiguration, IConfiguration configuration, String sectionName, DependencyContext dependencyContext)
   at Serilog.ConfigurationLoggerConfigurationExtensions.Configuration(LoggerSettingsConfiguration settingConfiguration, IConfiguration configuration, DependencyContext dependencyContext)

**Comment by bartelink** [comment]
You'll get this resolved quickest and easiest by logging this as an issue on stackoverflow.com with as much detail as possible and tagging it `serilog`. Feel free to paste a link here when that's done, but you'll definitely get an answer there quicker than you will here, without burning the valuable time of the maintainers on something that's likely to have a reasonable solution without treating it as a bug as such (you may well decide at the end that the only proper resolution is to have a change to Serilog in the end, but at least the maintainers will have a full discussion and repro to refer to, rather than a badly formatted issue in the wrong repo)
