### ISSUE TITLE
Logging multidimensional 2d array fails silently

### ISSUE THREAD

**Issue by emphasis87** [serilog/serilog#2019]
This fails silently:

```csharp
var a = new object[1, 1]{ { "a" } };
Log.Error("{@Value}", a);
```

Is this expected behavior? I would expect this:
`[["a"]]`

**Comment by nblumhardt** [comment]
Thanks for the report! The error behind the scenes is:

```
2024-03-01T21:21:16.5639620Z Exception caught while converting property value: System.ArgumentException: Array was not a one-dimensional array.
   at System.Array.GetValue(Int32 index)
   at Serilog.Capturing.PropertyValueConverter.TryConvertEnumerable(Object value, Type type, Destructuring destructuring, LogEventPropertyValue& result)
   at Serilog.Capturing.PropertyValueConverter.CreatePropertyValue(Object value, Destructuring destructuring, Int32 depth)
   at Serilog.Capturing.PropertyValueConverter.CreatePropertyValue(Object value, Destructuring destructuring)
```

In my test project I do see an event - it's:

```
[07:21:16 ERR] Capturing the property value threw an exception: ArgumentException
```

(The message there is what's substituted into the `Value` property.)

**Comment by chidamparam** [comment]
Can someone guide me to recreate and analyze the above issue so that I will go through the code and fix it
