### ISSUE TITLE
[ElasticSearchSink] Capturing a WCF EndpointNotFoundException will disable/kill logging

### ISSUE THREAD

**Issue by rvlieshout** [serilog/serilog#296]
When I try to log a WCF call exception, if fails and future logging fails too.

pseudocode:

``` csharp
try
{
    using (var proxy = new WcfProxy()) proxy.add(1, 2);
}
catch (EndpointNotFoundException ep)
{
    Log.Error(ep, "Endpoint not found.");
}
```

This will result in an endless stream of console messages (`Serilog.Debugging.SelfLog.Out = Console.Out`):

```
...
2014-11-20T07:27:34 Exception while emitting periodic batch from Serilog.Sinks.ElasticSearch.ElasticSearchSink: System.InvalidOperationException: Method may only be called on a Type for which Type.IsGenericParameter is true.
   at System.RuntimeType.get_DeclaringMethod()
   at lambda_method(Closure , Object )
   at Elasticsearch.Net.Serialization.ReflectionUtils.<>c__DisplayClassd.<GetGetMethodByExpression>b__c(Object source) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1863
   at Elasticsearch.Net.Serialization.PocoJsonSerializerStrategy.TrySerializeUnknownTypes(Object input, Object& output) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1465
   at Elasticsearch.Net.Serialization.PocoJsonSerializerStrategy.TrySerializeNonPrimitiveObject(Object input, Object& output) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1278
   at Elasticsearch.Net.Serialization.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1016
   at Elasticsearch.Net.Serialization.SimpleJson.SerializeObject(IJsonSerializerStrategy jsonSerializerStrategy, IEnumerable keys, IEnumerable values, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1044
   at Elasticsearch.Net.Serialization.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 993
   at Elasticsearch.Net.Serialization.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1018
   at Elasticsearch.Net.Serialization.SimpleJson.SerializeObject(IJsonSerializerStrategy jsonSerializerStrategy, IEnumerable keys, IEnumerable values, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1044
   at Elasticsearch.Net.Serialization.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 993
   at Elasticsearch.Net.Serialization.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1018
   at Elasticsearch.Net.Serialization.SimpleJson.SerializeObject(IJsonSerializerStrategy jsonSerializerStrategy, IEnumerable keys, IEnumerable values, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1044
   at Elasticsearch.Net.Serialization.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 993
   at Elasticsearch.Net.Serialization.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1018
   at Elasticsearch.Net.Serialization.SimpleJson.SerializeObject(IJsonSerializerStrategy jsonSerializerStrategy, IEnumerable keys, IEnumerable values, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1044
   at Elasticsearch.Net.Serialization.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 993
   at Elasticsearch.Net.Serialization.SimpleJson.SerializeObject(Object json, IJsonSerializerStrategy jsonSerializerStrategy) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 582
   at Elasticsearch.Net.Serialization.SimpleJson.SerializeObject(Object json) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 588
   at Elasticsearch.Net.Serialization.ElasticsearchDefaultSerializer.Serialize(Object data, SerializationFormatting formatting) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\ElasticsearchDefaultSerializer.cs:line 98
   at Elasticsearch.Net.Connection.Transport.<PostData>b__a(Object soo) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\Transport.cs:line 295
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at Elasticsearch.Net.Connection.Transport.PostData(Object data) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\Transport.cs:line 294
   at Elasticsearch.Net.Connection.Transport.DoRequest[T](String method, String path, Object data, IRequestParameters requestParameters) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\Transport.cs:line 306
   at Elasticsearch.Net.ElasticsearchClient.DoRequest[T](String method, String path, Object data, IRequestParameters requestParameters) in c:\code\elasticsearch-net\src\Elasticsearch.Net\ElasticsearchClient.cs:line 65
   at Elasticsearch.Net.ElasticsearchClient.Bulk(Object body, Func`2 requestParameters) in c:\code\elasticsearch-net\src\Elasticsearch.Net\ElasticsearchClient.Generated.cs:line 255
   at Serilog.Sinks.ElasticSearch.ElasticSearchSink.EmitBatch(IEnumerable`1 events)
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.OnTick() in c:\projects\serilog\src\Serilog.FullNetFx\Sinks\PeriodicBatching\PeriodicBatchingSink.cs:line 152
A first chance exception of type 'System.InvalidOperationException' occurred in mscorlib.dll
2014-11-20T07:27:45 Exception while emitting periodic batch from Serilog.Sinks.ElasticSearch.ElasticSearchSink: System.InvalidOperationException: Method may only be called on a Type for which Type.IsGenericParameter is true.
   at System.RuntimeType.get_DeclaringMethod()
   at lambda_method(Closure , Object )
   at Elasticsearch.Net.Serialization.ReflectionUtils.<>c__DisplayClassd.<GetGetMethodByExpression>b__c(Object source) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1863
   at Elasticsearch.Net.Serialization.PocoJsonSerializerStrategy.TrySerializeUnknownTypes(Object input, Object& output) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1465
   at Elasticsearch.Net.Serialization.PocoJsonSerializerStrategy.TrySerializeNonPrimitiveObject(Object input, Object& output) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1278
   at Elasticsearch.Net.Serialization.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1016
   at Elasticsearch.Net.Serialization.SimpleJson.SerializeObject(IJsonSerializerStrategy jsonSerializerStrategy, IEnumerable keys, IEnumerable values, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1044
   at Elasticsearch.Net.Serialization.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 993
   at Elasticsearch.Net.Serialization.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1018
   at Elasticsearch.Net.Serialization.SimpleJson.SerializeObject(IJsonSerializerStrategy jsonSerializerStrategy, IEnumerable keys, IEnumerable values, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1044
   at Elasticsearch.Net.Serialization.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 993
   at Elasticsearch.Net.Serialization.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1018
   at Elasticsearch.Net.Serialization.SimpleJson.SerializeObject(IJsonSerializerStrategy jsonSerializerStrategy, IEnumerable keys, IEnumerable values, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1044
   at Elasticsearch.Net.Serialization.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 993
   at Elasticsearch.Net.Serialization.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1018
   at Elasticsearch.Net.Serialization.SimpleJson.SerializeObject(IJsonSerializerStrategy jsonSerializerStrategy, IEnumerable keys, IEnumerable values, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 1044
   at Elasticsearch.Net.Serialization.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 993
   at Elasticsearch.Net.Serialization.SimpleJson.SerializeObject(Object json, IJsonSerializerStrategy jsonSerializerStrategy) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 582
   at Elasticsearch.Net.Serialization.SimpleJson.SerializeObject(Object json) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\SimpleJson.cs:line 588
   at Elasticsearch.Net.Serialization.ElasticsearchDefaultSerializer.Serialize(Object data, SerializationFormatting formatting) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Serialization\ElasticsearchDefaultSerializer.cs:line 98
   at Elasticsearch.Net.Connection.Transport.<PostData>b__a(Object soo) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\Transport.cs:line 295
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at Elasticsearch.Net.Connection.Transport.PostData(Object data) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\Transport.cs:line 294
   at Elasticsearch.Net.Connection.Transport.DoRequest[T](String method, String path, Object data, IRequestParameters requestParameters) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\Transport.cs:line 306
   at Elasticsearch.Net.ElasticsearchClient.DoRequest[T](String method, String path, Object data, IRequestParameters requestParameters) in c:\code\elasticsearch-net\src\Elasticsearch.Net\ElasticsearchClient.cs:line 65
   at Elasticsearch.Net.ElasticsearchClient.Bulk(Object body, Func`2 requestParameters) in c:\code\elasticsearch-net\src\Elasticsearch.Net\ElasticsearchClient.Generated.cs:line 255
   at Serilog.Sinks.ElasticSearch.ElasticSearchSink.EmitBatch(IEnumerable`1 events)
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.OnTick() in c:\projects\serilog\src\Serilog.FullNetFx\Sinks\PeriodicBatching\PeriodicBatchingSink.cs:line 152
A first chance exception of type 'System.InvalidOperationException' occurred in mscorlib.dll
...
```

Misc:
- .NET Target: 4.5.1
- Serilog NuGet Package: 1.4.18
- Serilog.Sinks.ElasticSearch NuGet Package: 1.4.18
- Elasticsearch.Net NuGet Package: 1.2.3

**Comment by peske** [comment]
Similar here. Already posted at https://github.com/elastic/elasticsearch-net/issues/1228

**Comment by nblumhardt** [comment]
Hi @peske - your stack trace on the other thread doesn't mention Serilog - are you seeing this issue with the Serilog ES sink, or just the standalone ES client? Thanks!

**Comment by peske** [comment]
Huh, sorry!!! My bad...
