### ISSUE TITLE
Elasticsearch 1.4.4 - fields seems to be a reserved word?

### ISSUE THREAD

**Issue by poulfoged** [serilog/serilog#398]
Now, this may be a Elasticsearch issue.

A simple log like this:

   logger.Information("User {@user} unable to pay order {@order}", currentUser, currentOrder);

Gives me this exception from Elasticsearch:

[2015-03-01 14:19:08,892][DEBUG][action.bulk              ] [Cadaver] [logstash-2015.03.01][3] failed to execute bulk item (index) index {[logstash-2015.03.01][logevent][AUvVfYhcsI1w9u-UQih4], source[
{"@timestamp":"2015-03-01T14:12:16.6855736+01:00","level":"Information","messageTemplate":"User {@user} unable to pay order {@order}","message":"User User { Id: 2, Name: \"Spock\" } unable to pay orde
r Order { Id: 7, Amount: 100 }","fields":{"user":{"_typeTag":"User","Id":2,"Name":"Spock"},"order":{"_typeTag":"Order","Id":7,"Amount":100}}}]}
org.elasticsearch.index.mapper.MapperParsingException: failed to parse [fields.user]
        at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:416)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeObject(ObjectMapper.java:557)
        at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:490)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeObject(ObjectMapper.java:557)
        at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:490)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:542)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:491)
        at org.elasticsearch.index.shard.service.InternalIndexShard.prepareCreate(InternalIndexShard.java:392)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:444)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:150)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:512)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:419)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.ElasticsearchIllegalArgumentException: unknown property [_typeTag]
        at org.elasticsearch.index.mapper.core.StringFieldMapper.parseCreateFieldForString(StringFieldMapper.java:331)
        at org.elasticsearch.index.mapper.core.StringFieldMapper.parseCreateField(StringFieldMapper.java:277)
        at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:406)
        ... 14 more

Version info:

    "status": 200,
    "name": "Margali Szardos",
    "cluster_name": "elasticsearch",
    "version": 

    {
        "number": "1.4.4",
        "build_hash": "c88f77ffc81301dfa9dfd81ca2232f09588bd512",
        "build_timestamp": "2015-02-19T13:05:36Z",
        "build_snapshot": false,
        "lucene_version": "4.10.3"
    },
    "tagline": "You Know, for Search"

**Comment by mivano** [comment]
Do you already have data in that index and if so, what type is the fields.user property?

**Comment by poulfoged** [comment]
Hm.. I thought that the index was empty, just tried with a empty instance, and that worked. 

My mistake.

**Comment by mivano** [comment]
Good to hear. Looks like a case of mixed property types (string vs object). For v2 we are looking into this as it is a bit tricky to see when this is happing.

**Comment by ThomasArdal** [comment]
I just experienced the exact same error:

	org.elasticsearch.index.mapper.MapperParsingException: failed to parse [fields.site.FrequencyResolution]
		at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:414)
		at org.elasticsearch.index.mapper.object.ObjectMapper.serializeObject(ObjectMapper.java:549)
		at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:491)
		at org.elasticsearch.index.mapper.object.ObjectMapper.serializeObject(ObjectMapper.java:549)
		at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:491)
		at org.elasticsearch.index.mapper.object.ObjectMapper.serializeObject(ObjectMapper.java:549)
		at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:491)
		at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:542)
		at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:491)
		at org.elasticsearch.index.shard.service.InternalIndexShard.prepareCreate(InternalIndexShard.java:376)
		at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:451)
		at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:157)
		at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:535)
		at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:434)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
		at java.lang.Thread.run(Unknown Source)
	Caused by: org.elasticsearch.ElasticsearchIllegalArgumentException: unknown property [_typeTag]
		at org.elasticsearch.index.mapper.core.LongFieldMapper.innerParseCreateField(LongFieldMapper.java:289)
		at org.elasticsearch.index.mapper.core.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:223)
		at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:404)
		... 16 more

In my case I think that the error is caused by the core type selected for [fields.site.FrequencyResolution] which is long. But the code I'm actually using to fill in this field is a double.

Sadly, I've tried re-creating the problem by creating a simple application logging a message through serilog with a long. Observed that the mapping is generated with the long core type. Then updated my code to log the same message but with a double value in the previous long property. No problem, the double value is successfully logged.
