### ISSUE TITLE
Unmangle Async/Await stacktraces

### ISSUE THREAD

**Issue by oliverjanik** [serilog/serilog#521]
I don't know if there is a solution to this out there or if it can be even done.

When I log exceptions, my logs tend to have a lot of these:

```
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.<ExecuteAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Utilities.TaskExtensions.CultureAwaiter`1.GetResult()
   at System.Data.Entity.Core.Objects.ObjectContext.<ExecuteInTransactionAsync>d__3d`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Utilities.TaskExtensions.CultureAwaiter`1.GetResult()
   at System.Data.Entity.Infrastructure.DbExecutionStrategy.<ProtectedExecuteAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Utilities.TaskExtensions.CultureAwaiter`1.GetResult()
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<GetResultsAsync>d__e.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Utilities.TaskExtensions.CultureAwaiter`1.GetResult()
   at System.Data.Entity.Internal.LazyAsyncEnumerator`1.<FirstMoveNextAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.<FirstOrDefaultAsync>d__25`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Identity.UserValidator`2.<ValidateUserName>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Identity.UserValidator`2.<ValidateAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Identity.UserManager`2.<CreateAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Identity.UserManager`2.<CreateAsync>d__d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Tilt.Diabetes.Services.Controllers.UsersController.<Register>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Tilt.Diabetes.Services.Auth.BasicChallengeResult.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.AuthenticationFilterResult.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
```

Is there anyway to get cleaner stacktraces for async/await that understand the context?

**Comment by nblumhardt** [comment]
Hi Oliver - unfortunately I think this is outside Serilog's control, but I'd love to hear any ideas around this :+1:

**Comment by stephendrew** [comment]
I have code that does this stripping - if it's outside Serilog's control, what would be the best way to hook up this code so that any call to Log.Error(Exception, ...)  etc applies it?

**Comment by oliverjanik** [comment]
Interesting can you post a gist?

**Comment by joelweiss** [comment]
Check out [AsyncFriendlyStackTrace](https://github.com/aelij/AsyncFriendlyStackTrace)

**Comment by nblumhardt** [comment]
@joelweiss very impressive!

Reopening, since it'd be great to have a well-known way to plug this in, even if it's a bit "fuzzy" to do in the core (and relies on language-specific routines right now).

One thing you could do today, for the text-based sinks, is create an enricher that uses the library linked above and adds a `AsyncFriendlyException` property to any event that has an `Exception` property:

```csharp

// Install-Package AsyncFriendlyStackTrace
// .Enrich.With<AsyncFriendlyExceptionEnricher>()

class AsyncFriendlyExceptionEnricher : ILogEventEnricher
{
    public void Enrich(LogEvent logEvent, ILogEventPropertyFactory propertyFactory)
    {
        if (logEvent.Exception == null) return;

        logEvent.AddPropertyIfAbsent(propertyFactory.CreateProperty(
            "AsyncFriendlyException", logEvent.Exception.ToAsyncString()));
    }
}
```

`"{AsyncFriendlyException}"` could then appear in text output - console/file sinks etc., without any special modification.

It'd be nice to go a step further and allow exception formatting to be plugged into the JSON-based sinks. I'll re-open this ticket and hopefully we'll get some experience/feedback on how well this works with the approach above :-)

**Comment by nblumhardt** [comment]
Discussing with @merbla, don't think there's a proposal active right now that will work for Serilog core, but if you have any ideas for moving this forwards please jump right in here.

**Comment by camp-007** [comment]
The work around of adding an additional property to the log event for "AsyncFriendlyException" ends up yielding two different stack traces in the log data.  This works, but doesn't yield the best end user experience.  Especially given some sinks will perform special treatment/formatting of the built in stack trace, it may still be rendered very prominently (as in the case of Seq).  

If I'm understanding things properly, Serilog.Core just carries an exception object and then the Sink implementations are left to decide what to do with it (mostly calling Exception.ToString() I presume).  I don't know what the proper api/abstraction should be, but if it could be assumed that all sinks will ultimately need/use a string representation of the exception details, then perhaps Serilog.Core could provide a way for the user to configure a Func<Exception, string> that instructs the Sink on how to convert the exception to text.  This of course would require the Sinks to implement support for this and be able to optionally chose between the provided Func vs the built in Exception.ToString().

So perhaps this could be configured using something like:

    Log.Logger = new LoggerConfiguration()
    .Destructure.ExceptionsUsing(ex => ex.ToAsyncString())
    .CreateLogger();

(Sorry, the Destructure configuration may not be the appropriate concept, but the idea would be to provide an overriding func at the time of configuration).

Just a thought.  Ultimately this is a .NET Framework issue.  I get *why* the stack traces end up the way they do, but this will eventually need to be addressed as it just introduces so much noise and makes debugging so much harder than it needs to be. I'd hope/expect for an eventual resolution from the MS team (https://github.com/dotnet/corefx/issues/1370)

**Comment by nblumhardt** [comment]
Reopening again, even if it's just to track the linked dotnet/corefx ticket for now. Ideally we'll align with some upstream support there; if it flounders then adding some notion of a custom formatter for exceptions (or perhaps subverting `IFormatProvider` ;-) ) could do the job. Thanks @camp-007.

**Comment by joelweiss** [comment]
Now you can use [Serilog.Enrichers.Demystify](https://github.com/nblumhardt/serilog-enrichers-demystify)

**Comment by nblumhardt** [comment]
👍 let's see how things go with that package; it's still experimental, so with a bit of usage we might have a better idea where this is heading :-) ... Let's close this old thread, finally!
