### ISSUE TITLE
ElasticSearch Sink Exception Prevents Logging

### ISSUE THREAD

**Issue by drusellers** [serilog/serilog#556]
We have our Serilog sinks built of of several composed sinks. One of which is the ElasticSearch sink. At start up if the ES sink cannot connect to ES (in this case due to a firewall rule), the other sinks fail to write any data as well, in this case the file loggers.

```
Configuration = new LoggerConfiguration();

            if (config.LogToConsole)
            {
                //log to console
                Configuration.WriteTo.Console(
                    outputTemplate:
                        "{Timestamp:yyyy-MM-dd HH:mm:ss} {RequestId} [{Level}] {Message}{NewLine}{Exception}",
                    restrictedToMinimumLevel: LogEventLevel.Information);
            }

            //elastic search
            Configuration.WriteTo.Elasticsearch(new ElasticsearchSinkOptions(config.ElasticSearch)
            {
                AutoRegisterTemplate = true,
                BufferBaseFilename = config.ElasticSearchBuffer,
                MinimumLogEventLevel = LogEventLevel.Verbose,
            })
                ;

            if (!string.IsNullOrWhiteSpace(config.LogPath))
            {
                Configuration.
                    WriteTo.Sink(new RollingFileSink(config.LogPath, new JsonFormatter(), 2097152, 10, Encoding.UTF8));
            }

```

**Comment by nblumhardt** [comment]
cc @serilog/owners-elasticsearch

**Comment by nblumhardt** [comment]
@mivano @Mpdreamz any thoughts on this one?

(Also, I am starting to think it's time to open the issue tracker on the ES sink repo :-))

**Comment by mivano** [comment]
Sorry, missed this one. The autoregister might fail, but we fixed that in 2.0.37 (https://github.com/serilog/serilog-sinks-elasticsearch/blob/master/CHANGES.md). So which version are you using?

**Comment by drusellers** [comment]
@mivano 2.0.37

**Comment by mivano** [comment]
And upping to latest version? It should be fixed in that one though. You have an exception call stack for me?

**Comment by drusellers** [comment]
@mivano Ok, just upgraded to `2.0.70` (clean solution, rebuild) then tried to launch my application with Elastic Search process killed off. I then get the following error.

```
System.Net.WebException
Unable to connect to the remote server
-- No connection could be made because the target machine actively refused it 127.0.0.1:9200
   at System.Net.HttpWebRequest.GetResponse()
   at Elasticsearch.Net.Connection.HttpConnection.DoSynchronousRequest(HttpWebRequest request, Byte[] data, IRequestConfiguration requestSpecificConfig) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\HttpConnection.cs:line 266
   at Elasticsearch.Net.ExceptionExtensions.RethrowKeepingStackTrace(Exception exception) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Extensions\ExceptionExtensions.cs:line 21
   at Elasticsearch.Net.Connection.RequestHandlers.RequestHandler.ReturnStreamOrVoidResponse[T](TransportRequestState`1 requestState, ElasticsearchResponse`1 streamResponse) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\RequestHandlers\RequestHandler.cs:line 69
   at Elasticsearch.Net.Connection.RequestHandlers.RequestHandler.CoordinateRequest[T](TransportRequestState`1 requestState, Int32 maxRetries, Int32 retried, Boolean& aliveResponse) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\RequestHandlers\RequestHandler.cs:line 134
   at Elasticsearch.Net.Connection.RequestHandlers.RequestHandler.DoRequest[T](TransportRequestState`1 requestState) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\RequestHandlers\RequestHandler.cs:line 175
   at Elasticsearch.Net.Connection.RequestHandlers.RequestHandler.Request[T](TransportRequestState`1 requestState, Object data) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\RequestHandlers\RequestHandler.cs:line 34
   at Elasticsearch.Net.Connection.Transport.DoRequest[T](String method, String path, Object data, IRequestParameters requestParameters) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\Transport.cs:line 343
   at Elasticsearch.Net.ElasticsearchClient.DoRequest[T](String method, String path, Object data, IRequestParameters requestParameters) in c:\code\elasticsearch-net\src\Elasticsearch.Net\ElasticsearchClient.cs:line 65
   at Elasticsearch.Net.ElasticsearchClient.IndicesExistsTemplateForAll[T](String name, Func`2 requestParameters) in c:\code\elasticsearch-net\src\Elasticsearch.Net\ElasticsearchClient.Generated.cs:line 13214
   at Serilog.Sinks.Elasticsearch.ElasticsearchSinkState.RegisterTemplateIfNeeded()
```

**Comment by mivano** [comment]
I tried to reproduce your scenario, but I cannot. What I did; create new command line application, install Serilog.Sinks.Elasticsearch (which will give me 2.0.70) and I add the following code

```csharp
 class Program
    {
        static void Main(string[] args)
        {
            Serilog.Debugging.SelfLog.Out = Console.Out;

            Log.Logger = new LoggerConfiguration()
               .WriteTo.Elasticsearch(new ElasticsearchSinkOptions(new Uri("http://localhost:9200"))
               {
                   AutoRegisterTemplate = true
               })
               .MinimumLevel.Debug()
               .CreateLogger();

            //Log.Debug("Debug");
            //Log.Information("Info");
            //Log.Warning("Warning");
            //Log.Error("Error");

            Console.ReadLine();
        }
    }
```

When I run this (with ES of course stopped), I do see the selflog message, but it does not crash the application. The whole RegisterTemplateIfNeeded code is wrapped inside a try/catch. You sure you do not break on all errors?

This is the output I get in the command window:

```
2015-12-14T22:32:56 Failed to create the template. System.Net.WebException: Unab
le to connect to the remote server ---> System.Net.Sockets.SocketException: No c
onnection could be made because the target machine actively refused it 127.0.0.1
:9200
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddre
ss socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Sock
et s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state,
IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.Connection.Transport.ThrowOrGetErrorFromStreamResponse[T
](TransportRequestState`1 requestState, ElasticsearchResponse`1 streamResponse)
in c:\Users\gmarz\code\elasticsearch-net\src\Elasticsearch.Net\Connection\Transp
ort.cs:line 680
   at Elasticsearch.Net.Connection.Transport.DoRequest[T](TransportRequestState`
1 requestState) in c:\Users\gmarz\code\elasticsearch-net\src\Elasticsearch.Net\C
onnection\Transport.cs:line 376
   at Elasticsearch.Net.Connection.Transport.DoRequest[T](String method, String
path, Object data, IRequestParameters requestParameters) in c:\Users\gmarz\code\
elasticsearch-net\src\Elasticsearch.Net\Connection\Transport.cs:line 309
   at Elasticsearch.Net.ElasticsearchClient.DoRequest[T](String method, String p
ath, Object data, IRequestParameters requestParameters) in c:\Users\gmarz\code\e
lasticsearch-net\src\Elasticsearch.Net\ElasticsearchClient.cs:line 65
   at Elasticsearch.Net.ElasticsearchClient.IndicesExistsTemplateForAll[T](Strin
g name, Func`2 requestParameters) in c:\Users\gmarz\code\elasticsearch-net\src\E
lasticsearch.Net\ElasticsearchClient.Generated.cs:line 12294
   at Serilog.Sinks.Elasticsearch.ElasticsearchSinkState.RegisterTemplateIfNeede
d()
```

Note the first sentence; it is the selflog reporting an issue, but not blocking.

My packages:

```xml
<packages>
  <package id="Elasticsearch.Net" version="1.1.2" targetFramework="net452" />
  <package id="Serilog" version="1.4.204" targetFramework="net452" />
  <package id="Serilog.Sinks.Elasticsearch" version="2.0.70" targetFramework="net452" />
</packages>
```

You see any differences in what I m doing? I also added the buffered sink option, but the same effect.

**Comment by drusellers** [comment]
Ok, when I run it now (after a `git clean -dfx`) I do in fact no longer get an exception. :+1: and I do believe that i had break on all exceptions :facepalm: Thank you guys I'm closing this issue now. :)

**Comment by mivano** [comment]
Great, otherwise I had no clue what was going on :-). BTW We are investigating other options to see what to do when the index could not be created (issue #453). Thanks for getting back to us.

**Comment by drusellers** [comment]
:) and thank you for all of your patience and support.
