### ISSUE TITLE
NullReferenceException in Serilog.Sinks.AzureTableStorage

### ISSUE THREAD

**Issue by CurufinweU** [serilog/serilog#620]
Hi all,

I found NullReferenceException when using Serilog.Sinks.AzureTableStorage.1.5.5

Stack trace:

```
 at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpWebRequestFactory.<GetPropertiesFromDictionary>b__5(KeyValuePair`2 kvp) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Table\Protocol\TableOperationHttpRequestFactory.cs:line 230
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpWebRequestFactory.<GetPropertiesWithKeys>d__9.MoveNext() in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Table\Protocol\TableOperationHttpRequestFactory.cs:line 248
   at Microsoft.Data.OData.JsonLight.ODataJsonLightPropertySerializer.WriteProperties(IEdmStructuredType owningType, IEnumerable`1 properties, Boolean isComplexValue, DuplicatePropertyNamesChecker duplicatePropertyNamesChecker, ProjectedPropertiesAnnotation projectedProperties)
   at Microsoft.Data.OData.JsonLight.ODataJsonLightWriter.EndEntry(ODataEntry entry)
   at Microsoft.Data.OData.ODataWriterCore.<WriteEndImplementation>b__16()
   at Microsoft.Data.OData.ODataWriterCore.InterceptException(Action action)
   at Microsoft.Data.OData.ODataWriterCore.WriteEndImplementation()
   at Microsoft.Data.OData.ODataWriterCore.WriteEnd()
   at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpWebRequestFactory.WriteOdataEntity(ITableEntity entity, TableOperationType operationType, OperationContext ctx, ODataWriter writer, TableRequestOptions options) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Table\Protocol\TableOperationHttpRequestFactory.cs:line 211
   at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpWebRequestFactory.BuildRequestForTableOperation(Uri uri, UriQueryBuilder builder, IBufferManager bufferManager, Nullable`1 timeout, TableOperation operation, Boolean useVersionHeader, OperationContext ctx, TableRequestOptions options, String accountName) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Table\Protocol\TableOperationHttpRequestFactory.cs:line 113
   at Microsoft.WindowsAzure.Storage.Table.TableOperation.<>c__DisplayClass4.<InsertImpl>b__1(Uri uri, UriQueryBuilder builder, Nullable`1 timeout, Boolean useVersionHeader, OperationContext ctx) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Table\TableOperation.cs:line 128
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ProcessStartOfRequest[T](ExecutionState`1 executionState, String startLogMessage) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 858
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 619

 at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 633
   at Microsoft.WindowsAzure.Storage.Table.TableOperation.Execute(CloudTableClient client, CloudTable table, TableRequestOptions requestOptions, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Table\TableOperation.cs:line 41
   at Microsoft.WindowsAzure.Storage.Table.CloudTable.Execute(TableOperation operation, TableRequestOptions requestOptions, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Table\CloudTable.cs:line 53
   at Serilog.Sinks.AzureTableStorage.AzureTableStorageWithPropertiesSink.Emit(LogEvent logEvent)
   at Serilog.Core.Sinks.SafeAggregateSink.Emit(LogEvent logEvent) in C:\projects\serilog\src\Serilog\Core\Sinks\SafeAggregateSink.cs:line 38
```

Exception happens when I use AzureTableStorageWithProperties and try to log "null" value as one of properties.
AzurePropertyFormatter.SimplifyScalar returns null (as EntityProperty return value) in this case but TableOperationHttpWebRequestFactory.GetPropertiesFromDictionary does not expect null values:

230             return properties.Select(kvp => new ODataProperty() { Name = kvp.Key, Value = kvp.Value.PropertyAsObject });  

Probably creating EntityProperty with null value inside would fix this problem.

**Comment by nblumhardt** [comment]
Thanks for the report, I think you're correct. Created PR https://github.com/serilog/serilog-sinks-azuretablestorage/pull/2 -- @robdmoore mind a quick sanity check?

PS - also re-enabled the issue tracker directly on the Azure Table Storage repo.

**Comment by robdmoore** [comment]
:thumbsup:
