### ISSUE TITLE
ElasticSearchDurableSink: allow concurrent use of the same buffer files pool

### ISSUE THREAD

**Issue by guillaume86** [serilog/serilog#624]
Hi,

I have a scenario where I need different processes to share the same buffer files pool concurrently.
I naively tried it but the selflog is reporting issues and it seems some buffer files are not sent (not modified for +1H).

Here's the exception reported in the selflog (the second one repeated every few seconds):

    2016-01-08T13:10:59 Rolling file target C:\PATH\Logs\buffer-20160108.json was locked, attempting to open next in sequence (attempt 1)
    2016-01-08T14:00:02 Exception while emitting periodic batch from Serilog.Sinks.Elasticsearch.ElasticsearchLogShipper: System.IO.IOException: The process cannot access the file 'C:\PATH\Logs\buffer-20160108.json' because it is being used by another process.
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.File.InternalDelete(String path, Boolean checkHost)
       at Serilog.Sinks.Elasticsearch.ElasticsearchLogShipper.OnTick()
    2016-01-08T14:00:10 Exception while emitting periodic batch from Serilog.Sinks.Elasticsearch.ElasticsearchLogShipper: System.IO.IOException: The process cannot access the file 'C:\PATH\Logs\buffer-20160108.json' because it is being used by another process.
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.File.InternalDelete(String path, Boolean checkHost)
       at Serilog.Sinks.Elasticsearch.ElasticsearchLogShipper.OnTick()

Is it expected behavior? Any idea how I could achieve that? (I guess the other solution is to have different buffer paths but I need to know how to migrate the buffer files to another active path when I stop a process)

To give details about my scenario:
I have a web application with different versions running on IIS (one version by app pool, one single log instance by app pool), I want to be able to: 
1) run several versions at the same time
2) let the other versions instances pick up the remainig buffer files when I shut down a version

**Comment by guillaume86** [comment]
Maybe a simpler solution is to provide a synchronous (or async with exception reporting) API to process buffer files, I could run that on remaining files after retiring an app pool, should I open another issue for that request?

**Comment by nblumhardt** [comment]
Hi @guillaume86, thanks for the note.

The buffering is single-process, so this is expected behaviour. I think in this case shipping the files from a separate process as you've suggested should work.

It's a substantial task to implement however so I don't think it's worth opening an issue at this point unless someone chimes in here with the desire to do the design/build/release work for it.

**Comment by guillaume86** [comment]
Thank you fell free to close

2016-02-11 23:02 UTC+01:00, Nicholas Blumhardt <notifications@github.com>:

**Comment by maruf-hossain** [comment]
Hello, I have a situation where I have multiple processes running with their own instance of serilog provider. But due to design constraints, all processes share the same buffer path. Is it possible to leverage the underlying file sink to enable bufferFileShare?
