### ISSUE TITLE
HttpRequestClientHostIPEnricher: Value does not fall within the expected range

### ISSUE THREAD

**Issue by vidarkongsli** [serilog/serilog#646]
Found the following stack trace in the self-log from time to time.
```
2016-01-25T14:18:13 Exception System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Web.Hosting.IIS7WorkerRequest.GetServerVariableInternal(String name)
   at SerilogWeb.Classic.Enrichers.HttpRequestClientHostIPEnricher.Enrich(LogEvent logEvent, ILogEventPropertyFactory propertyFactory)
   at Serilog.Core.Pipeline.Logger.Dispatch(LogEvent logEvent) in C:\projects\serilog\src\Serilog\Core\Pipeline\Logger.cs:line 163 caught while enriching Serilog.Events.LogEvent with SerilogWeb.Classic.Enrichers.HttpRequestClientHostIPEnricher.
```
Serilog 1.5.14
SerilogWeb.Classic 2.0.6

**Comment by nblumhardt** [comment]
Thanks for the report. It looks like this occurs when accessing properties of a request that is no longer valid. I think we'll need some kind of check around the code that reads this over in https://github.com/serilog-web/classic.

**Comment by nblumhardt** [comment]
This is part of the SerilogWeb codebase, so I've moved the issue to: https://github.com/serilog-web/classic/issues/26
