### ISSUE TITLE
Serilog + Logentries

### ISSUE THREAD

**Issue by KieranOBrien-R7** [serilog/serilog#704]
Issue with Serilog and LogEntries integration. I am able to successfully log to a local text file but I'm not having any luck logging to my new account in LogEntries. I'm using the correct LogEntries token for my new log... while debugging a unit test, it looks like my test integration is just sitting in the sink queue and not getting sent out. I having no other processes running on port 1000 after inspection. I've also used Fiddler to confirm that my test log is not getting sent out. Any suggestions?

**Comment by nblumhardt** [comment]
Thank you for the report - I'm not aware of anything that's likely to cause this. One thing you might try is disposing the logger at the completion of the test, to make sure any buffered events are flushed.

For the static logger that's:

```csharp
(Log.Logger as IDisposable)?.Dispose();
```

or on v2:

```csharp
Log.CloseAndFlush();
```

If you have an `ILogger` instance, casting to `IDisposable` and disposing will do it:

```csharp
(logger as IDisposable)?.Dispose();
```

Any luck?

**Comment by YetAnotherDev** [comment]
Hello,
I'm also having this issue. I tried your suggestion and flushed the logger but I'm still not seeing any messages logged.  In fact I never see the EmitBatch method called on the LogentiresSink class. I assume that is being called once the batch size is hit (50 by default) or the Period is hit(2 sec by default)?

I have used this combo in the past and it worked great.

**Comment by nblumhardt** [comment]
Thanks for the note @YetAnotherDev.

Is anyone familiar with logentries able to grab the source and step through this one? // cc @serilog/owners-logentries

**Comment by YetAnotherDev** [comment]
a quick note: the internal logger also does not log any errors while using the logentries sink.

**Comment by abrussak** [comment]
The sink looks to be working.
By default the sink logs via TCP over SSL on port 20000, so I'd check to ensure that your firewall isn't blocking outbound connections on that port. You could try disabling SSL which will cause it to send data via port 10000. [Code](https://github.com/serilog/serilog-sinks-logentries/blob/master/src/Serilog.Sinks.Logentries/Sinks/Logentries/LeClient.cs#L51-L55)

![image](https://cloud.githubusercontent.com/assets/890967/14154098/a96caa74-f66f-11e5-99fe-53ba3e55d541.png)

Here's the code I'm using in a console app.
``` csharp
class Program
{
	static void Main(string[] args)
	{
		var logger = new LoggerConfiguration()
			.MinimumLevel.Verbose()
			.WriteTo.ColoredConsole()
			.WriteTo.Logentries("Insert_Key_Here")
			.CreateLogger();

		Log.Logger = logger;
		Serilog.Debugging.SelfLog.Out = Console.Out;

		var point = new Point
		{
			X = 1,
			Y = 2
		};

		Log.Logger.Verbose("Verbose message, Point: {@Point}", point);
		Log.Logger.Information("Information message, Point: {@Point}", point);
		Log.Logger.Warning("Warning message, Point: {@Point}", point);
		Log.Logger.Error("Error message, Point: {@Point}", point);
		Log.Logger.Fatal("Fatal message, Point: {@Point}", point);
	}
}

class Point
{
	public double X { get; set; }
	public double Y { get; set; }
}
```

@nblumhardt If I edit my console app to immediately dispose of the logger after logging:
```
(Log.Logger as IDisposable)?.Dispose();
```
I run into an null ref exception at the [Flush() method](https://github.com/serilog/serilog-sinks-logentries/blob/master/src/Serilog.Sinks.Logentries/Sinks/Logentries/LeClient.cs#L109)
The `ActiveStream` object isn't null so not completely sure what's throwing, most likely something in the stream.
Stack Trace
```
   at Serilog.Sinks.Logentries.LeClient.Flush() in D:\git\serilog-sinks-logentries\src\Serilog.Sinks.Logentries\Sinks\Logentries\LeClient.cs:line 109
   at Serilog.Sinks.Logentries.LogentriesSink.Dispose(Boolean disposing) in D:\git\serilog-sinks-logentries\src\Serilog.Sinks.Logentries\Sinks\Logentries\LogentriesSink.cs:line 134
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.Dispose() in c:\projects\serilog\src\Serilog.FullNetFx\Sinks\PeriodicBatching\PeriodicBatchingSink.cs:line 102
   at Serilog.LoggerConfiguration.<CreateLogger>b__6() in c:\projects\serilog\src\Serilog\LoggerConfiguration.cs:line 130
   at Serilog.Core.Pipeline.Logger.Dispose() in c:\projects\serilog\src\Serilog\Core\Pipeline\Logger.cs:line 249
   at LogEntriesConsoleTest.Program.Main(String[] args) in D:\Visual Studio Projects\LogEntriesConsoleTest\LogEntriesConsoleTest\Program.cs:line 44
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

If I put a sleep of 1 second before disposing, it works fine.

**Comment by YetAnotherDev** [comment]
thanks @abrussak, sorry for the false alarm.  I opened up 20000 and everything started working.

**Comment by nblumhardt** [comment]
@abrussak thanks for jumping in! Glad to see it's all sorted @YetAnotherDev .

Added an issue for the flush/dispose problem here: https://github.com/serilog/serilog-sinks-logentries/issues/2
