### ISSUE TITLE
Invalid Enum formats cause issues

### ISSUE THREAD

**Issue by adamchester** [serilog/serilog#857]
The following [example](http://share.linqpad.net/urqmm2.linq) shows how the console sinks behave when an invalid format string is provided for an enum property:

``` csharp
void Main()
{
    var selfLogWriter = new StringWriter();
    Serilog.Debugging.SelfLog.Enable(selfLogWriter.Write);

    var logger = new LoggerConfiguration()
        .WriteTo.ColoredConsole()
        .WriteTo.LiterateConsole()
        .WriteTo.Console()
        .CreateLogger();

    foreach (var enumValue in Enum.GetValues(typeof(System.ConsoleColor)).Cast<System.ConsoleColor>())
    {
        logger.Information("test bad enum format {enum:asdf}", enumValue);
    }

    Console.WriteLine();
    Console.WriteLine(selfLogWriter.ToString());
}
```

The output is missing the enum property and missing a final newline:

```
2016-09-10 07:27:19 [Information] test bad enum format [07:27:19 INF] test bad enum format 2016-09-10 07:27:19 [Information] test bad enum format [07:27:19 INF] test bad enum format 2016-09-10 07:27:19 [Information] test bad enum format [07:27:19 INF] test bad enum format 2016-09-10 07:27:19 [Information] test bad enum format [07:27:19 INF] test bad enum format 2016-09-10 07:27:19 [Information] test bad enum format [07:27:19 INF] test bad enum format 2016-09-10 07:27:19 [Information] test bad enum format [07:27:19 INF] test bad enum format 2016-09-10 07:27:19 [Information] test bad enum format [07:27:19 INF] test bad enum format 2016-09-10 07:27:19 [Information] test bad enum format [07:27:19 INF] test bad enum format 2016-09-10 07:27:19 [Information] test bad enum format [07:27:19 INF] test bad enum format 2016-09-10 07:27:19 [Information] test bad enum format [07:27:19 INF] test bad enum format 2016-09-10 07:27:19 [Information] test bad enum format [07:27:19 INF] test bad enum format 2016-09-10 07:27:19 [Information] test bad enum format [07:27:19 INF] test bad enum format 2016-09-10 07:27:19 [Information] test bad enum format [07:27:19 INF] test bad enum format 2016-09-10 07:27:19 [Information] test bad enum format [07:27:19 INF] test bad enum format 2016-09-10 07:27:19 [Information] test bad enum format [07:27:19 INF] test bad enum format 2016-09-10 07:27:19 [Information] test bad enum format [07:27:19 INF] test bad enum format 
```

The self-log messages are:

```
2016-09-09T21:27:19.5727903Z Caught exception while emitting to sink Serilog.Sinks.SystemConsole.ColoredConsoleSink: System.FormatException: Format String can be only "G", "g", "X", "x", "F", "f", "D" or "d".
   at System.Enum.ToString(String format)
   at System.Enum.ToString(String format, IFormatProvider provider)
   at Serilog.Events.ScalarValue.Render(TextWriter output, String format, IFormatProvider formatProvider)
   at Serilog.Parsing.PropertyToken.Render(IReadOnlyDictionary`2 properties, TextWriter output, IFormatProvider formatProvider)
   at Serilog.Sinks.SystemConsole.ColoredConsoleSink.RenderMessageToken(LogEvent logEvent, Palette palette, TextWriter output)
   at Serilog.Sinks.SystemConsole.ColoredConsoleSink.Emit(LogEvent logEvent)
   at Serilog.Core.Sinks.SafeAggregateSink.Emit(LogEvent logEvent)2016-09-09T21:27:19.5757902Z Caught exception while emitting to sink 
```

I would expect this to be handled more gracefully. Suggestions on how to improve this are welcome.

**Comment by krajek** [comment]
In such cases I would expect any marker that error has occured. It may be something like ??? or #ERR.

**Comment by nblumhardt** [comment]
I think this is one of many, many formatting edge cases; perhaps `SelfLog` is good enough? May be preferable to trying to handle this broad class of problems in Serilog. @adamchester ?

**Comment by adamchester** [comment]
@nblumhardt  Seems fair, I haven't been able to think up a decent, simple, reliable generic solution. Closing.
