### ISSUE TITLE
Latest Serilog with latest Nuget.exe causes 'Serilog' already has a dependency defined for 'Microsoft.CSharp'

### ISSUE THREAD

**Issue by dgwaldo** [serilog/serilog#919]
Haven't pinned this one down yet, trying to push a local NuGet package that depends on Serilog.  This is the error that occurs.

2016-12-13T02:12:32.1297869Z Add file 'C:\TfsData\Build\Stage\_work\6\s\LSC.Infrastructure.Logging\bin\Release\LSC.Infrastructure.Logging.dll' to package as 'lib\net452\LSC.Infrastructure.Logging.dll'
2016-12-13T02:12:32.1907921Z ##[error]System.InvalidOperationException: 'Serilog' already has a dependency defined for 'Microsoft.CSharp'.
2016-12-13T02:12:32.1917922Z ##[error]   at NuGet.Manifest.ValidateDependencySets(IPackageMetadata metadata)
2016-12-13T02:12:32.1927916Z ##[error]   at NuGet.Manifest.Validate(Manifest manifest)
2016-12-13T02:12:32.1927916Z ##[error]   at NuGet.Manifest.ReadFrom(Stream stream, IPropertyProvider propertyProvider, Boolean validateSchema)
2016-12-13T02:12:32.1937926Z ##[error]   at NuGet.LocalPackage.ReadManifest(Stream manifestStream)
2016-12-13T02:12:32.1937926Z ##[error]   at NuGet.OptimizedZipPackage.EnsureManifest()
2016-12-13T02:12:32.1947911Z ##[error]   at NuGet.OptimizedZipPackage..ctor(IFileSystem fileSystem, String packagePath, IFileSystem expandedFileSystem)
2016-12-13T02:12:32.1947911Z ##[error]   at NuGet.SharedPackageRepository.OpenPackage(String path)
2016-12-13T02:12:32.1957911Z ##[error]   at NuGet.LocalPackageRepository.GetPackage(Func`2 openPackage, String path)
2016-12-13T02:12:32.1957911Z ##[error]   at NuGet.LocalPackageRepository.<>c__DisplayClass13.<FindPackage>b__f(String path)
2016-12-13T02:12:32.1967918Z ##[error]   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
2016-12-13T02:12:32.1967918Z ##[error]   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
2016-12-13T02:12:32.1977921Z ##[error]   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
2016-12-13T02:12:32.1977921Z ##[error]   at NuGet.LocalPackageRepository.FindPackage(Func`2 openPackage, String packageId, SemanticVersion version)
2016-12-13T02:12:32.1987915Z ##[error]   at NuGet.LocalPackageRepository.FindPackage(String packageId, SemanticVersion version)
2016-12-13T02:12:32.1987915Z ##[error]   at NuGet.SharedPackageRepository.FindPackage(String packageId, SemanticVersion version)
2016-12-13T02:12:32.1997922Z ##[error]   at NuGet.PackageRepositoryExtensions.FindPackage(IPackageRepository repository, String packageId, SemanticVersion version, IPackageConstraintProvider constraintProvider, Boolean allowPrereleaseVersions, Boolean allowUnlisted)
2016-12-13T02:12:32.1997922Z ##[error]   at NuGet.CommandLine.ProjectFactory.<>c__DisplayClass90_0.<AddFiles>b__0(PackageReference reference)
2016-12-13T02:12:32.2007984Z ##[error]   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
2016-12-13T02:12:32.2007984Z ##[error]   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
2016-12-13T02:12:32.2017895Z ##[error]   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
2016-12-13T02:12:32.2017895Z ##[error]   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
2016-12-13T02:12:32.2027955Z ##[error]   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
2016-12-13T02:12:32.2027955Z ##[error]   at NuGet.CommandLine.ProjectFactory.AddFiles(PackageBuilder builder, String itemType, String targetFolder)
2016-12-13T02:12:32.2037897Z ##[error]   at NuGet.CommandLine.ProjectFactory.<>c__DisplayClass55_0.<CreateBuilder>b__1(ProjectFactory p)
2016-12-13T02:12:32.2037897Z ##[error]   at NuGet.CommandLine.ProjectFactory.ApplyAction(Action`1 action)
2016-12-13T02:12:32.2047913Z ##[error]   at NuGet.CommandLine.ProjectFactory.CreateBuilder(String basePath)
2016-12-13T02:12:32.2047913Z ##[error]   at NuGet.CommandLine.PackCommand.BuildFromProjectFile(String path)
2016-12-13T02:12:32.2047913Z ##[error]   at NuGet.CommandLine.PackCommand.BuildPackage(String path)
2016-12-13T02:12:32.2057917Z ##[error]   at NuGet.CommandLine.PackCommand.ExecuteCommand()
2016-12-13T02:12:32.2057917Z ##[error]   at NuGet.CommandLine.Command.ExecuteCommandAsync()
2016-12-13T02:12:32.2067917Z ##[error]   at NuGet.CommandLine.Command.Execute()
2016-12-13T02:12:32.2067917Z ##[error]   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
2016-12-13T02:12:32.2127920Z ##[error]Unexpected exit code 1 returned from tool NuGet.exe

**Comment by nblumhardt** [comment]
Hi there! You need to update your NuGet.exe version (or the NuGet tools for Visual Studio, if that's what you're using).

```
nuget update -Self
```

Closing as duplicate, #806 IIRC, but please let me know if upgrading NuGet doesn't help. Thanks!

**Comment by dgwaldo** [comment]
Hi sorry, I guess I didn't mention that in my original ticket.  I've done the update, exact command you posted, it doesn't seem to get nuget to the latest greatest. Boosted it from 2.x to 3.4.4.1322.  Noticed that the latest is actually 3.5, http://www.nuget.org/ so trying that now.

**Comment by ATripathy1** [comment]
Hi Already tried updating to the latest nuget, which is 3.5 "Name             : Package Manager Host
Version          : 3.5.0.1996
InstanceId       : ac02c4e6-7c58-47ca-81ce-d16dcde804ca
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface"
